### ISSUE TITLE
The Y -Axis is not visible in portrait mode on the tokenLogger chart

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#1254]
**Steps to reproduce:**
1.Log into the app as snakessqa@gmail.com // 123456
2. Take the assessment for the  TL applet
3. Navigate to the Data tab
4. Observe the screen in portrait mode

**Actual result:** The Y -Axis is not visible in portrait mode on the tokenLogger chart
Video: https://www.screencast.com/t/btYmlsys
**Expected result:** The Y -Axis is displayed in portrait mode on the tokenLogger chart

**Environment:**
Staging
ML v 0.14.17
iPhone X // iOS 13.3
Pixel 4XL//Android 11

**Comment by sergeysemenuta** [comment]
The issue is fixed on the portrait mode
![2020-12-10_11-37-12.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/18164f89-40e0-4e97-bd12-219debc57c38)
Raised a separate ticket for landscape mode [1388](https://app.zenhub.com/workspaces/mindlogger-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-app/1388)

ML v 0.14.24
iPhone X // iOS 13.3
Pixel 4XL//Android 11
Galaxy s10/Android 9
