### ISSUE TITLE
The notifications are not fired in offline mode

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-app#1410]
**Preconditions:**
The events are scheduled  with notifications and the user is online

**Steps to reproduce:**
1. Log  in to the app
2. Turn off the Internet connection on the device
3. Wait for the notifications

**Actual result:**  The notifications are not fired in offline mode
**Expected result:** The notifications are fired in offline mode

**Note:** On other ios devices, notifications are fired in offline mode. Reproducible only on iPhone XR // iOS 13.2.3

**Environment:**
MindLogger app v 0.14.33 (253)
iPhone XR // iOS 13.2.3

**Comment by natalia-muzyka** [comment]
Reproducible on ML pilot v0.16.35
Notifications are displayed only after enabling the internet connection

iPhone XR // iOS 14.3"	
Samsung Galaxy S9 // Android 9.0"	
Pixel 3 XL // Android 10.0"

**Comment by natalia-muzyka** [comment]
Reproducible on ML v0.17.69 (staging)
Samsung S8 // Android 9

**Comment by natalia-muzyka** [comment]
Reproducible on ML v0.17.71 (staging)
Notifications are fired only after turning on the connection

iPhone 8 Plus // iOS 13.3
iPhone 11 // iOS 14.2
iPhone 7	// iOS 13.1.1
Samsung S7 // Android 8.0	
Samsung Tab S6 // Android 9
Pixel 3 XL	// Android 10.0

**Comment by natalia-muzyka** [comment]
@devbtech 
the issue is reproducible on 17.73 (staging)

**DBT(some users had completed some of the activities, but not today) steps:**
1. set up repeated daily three activities with reminder notifications:
daily (daily repeat)
events and goals (weekly repeat)
target behavior (monthly repeat)
2. save the schedule and refresh mobile app
3. turn off wifi on device
4. wait for a scheduled time

**Conditionals (Kimberly) (users haven't completed an activity):**
1. set up always available activity1
2. save the schedule and refresh mobile app
3. turn off wifi on device
4. wait for a scheduled time

Video(dbt):  https://www.screencast.com/t/R52t8cZJXY

account owner:
kimberly_ml@protonmail.com // 12345678
applets: DBT, Conditionals (kimberly)
accounts:
bernard_ml@protonmail.com	qwe123!!!
alyssia_ml@protonmail.com	qwertyuio
Applets password:	Qwe123!!!

Devices:
Samsung S7 // Android 8.0
Samsung Tab S6 // Android 9
iPhone 8 Plus // iOS 13.3

**Comment by natalia-muzyka** [comment]
Blocked by
https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-app/1442

**Comment by natalia-muzyka** [comment]
Still reproducible. Missing notifications are fired after resuming the internet connection.
Video: https://www.screencast.com/t/jPoMY4qPShjc

Devices:
Samsung S7 // Android 8.0
Samsung Tab S6 // Android 9
iPhone 8 Plus // iOS 13.3
iPhone 6S // iOS 14.4

**Comment by natalia-muzyka** [comment]
@devbtech The issue is still reproducible. Notifications aren't fired in offline mode. After resuming the internet connection some notifications are fired. For all the tested users any activity wasn't in progress or completed (at all).

Video (Samsung S7, iPhone 11, DBT1): https://www.screencast.com/t/xMWmwqqWL3a4
Video (Samsung Tab S6, iPhone SE 2020, DBT): https://www.screencast.com/t/5zvtfvnA9Odo

ML v0.18.7 (staging)
Devices:
Samsung S7 // Android 8.0
Samsung Tab S6 // Android 9
iPhone SE 2020 // iOS 14.2
iPhone 11 //  iOS 14.2

account owner:
kimberly_ml@protonmail.com 12345678
account users:
loui_ml@protonmail.com // 12345678
alyssia_ml@protonmail.com // qwertyuio
danielle_ml@protonmail.com	// qwe123!!!
applet: DBT, DBT (1)
Applet password: Qwe123!!!

**Comment by natalia-muzyka** [comment]
still reproducible:
Samsung S7 & iPad Air 2 WiFi: https://www.screencast.com/t/vkM4p6lLxzx
iPhone 12 pro max: https://www.screencast.com/t/FwchXJNSjub5

tested with existing applet EMA (on 12 pro max notification were fired, on Samsung S7 weren't).
tested with newly created applet: notifications weren't fired on any device.
notifications are shown randomly only after resuming the internet connection.

ML v0.18.11 (staging)
Samsung S7 // Android 8
iPad Air 2 WiFi // iOS 14.6
iPhone 12 Pro Max // iOS 15.0.1

kimberly_ml@protonmail.com // 12345678
applets:
EMA, notifications check
Applet password: Qwe123!!!

account users:
alyssia_ml@protonmail.com // qwertyuio
danielle_ml@protonmail.com // qwe123!!!

**Comment by natalia-muzyka** [comment]
@devbtech could you clarify, please, what was changed? I'm still not getting offline notifications.
Video (EMA): https://www.screencast.com/t/7svB1ltTJiY
Video (Geolocation test): 

applet owner: bernard_ml@protonmail.com	qwe123!!!
applets: EMA, Geolocation test
Applet password: Qwe123!!!
Devices:
iPhone 6s	14.4
Samsung Galaxy S7 SM-G930FD	8.0
iPad Pro (10,5-inch) MQDX2	15.0
Samsung Galaxy Tab S6 SM-T865	9.0

**Comment by natalia-muzyka** [comment]
Offline notifications still don't work. Checked on:
ML v0.18.20 staging
Samsung S7 // Android 8
Samsung S9 // Android 10
Samsung Tab S6 // Android 9
iPhone 6S // iOS 14.6
iPhone 8 Plus // iOS 13.3

video 1: https://www.screencast.com/t/NjKvqgI69
video 2: https://www.screencast.com/t/0QyfalhK
owner: kimberly_ml@protonmail.com // 1234567
applet: notifications check v2

**Comment by natalia-muzyka** [comment]
Verified as fixed: https://www.screencast.com/t/THaoImnF

Environment:
ML v0.19.2 staging
iPhone Xs Max// iOS 15.3
iPad Pro (10,5-inch) MQDX2 15.0
Samsung Galaxy S7 // Android 8
Samsung Galaxy Tab S6 SM-T865 9.0

**Comment by natalia-muzyka** [comment]
Notifications are not fired offline if:
1. app is in background
2. app is closed
3. app is in background, device is in sleep mode

Video (0.21.54 staging): https://www.screencast.com/t/YJelJFbt

Not reproduced for online notifications. Reproduced on prod (0.21.48).

**Environment:**
iPhone 13 // iOS 15.6
Google Pixel 5a // Android 11

ML v0.21.54 staging
user-stg@ml.com / 123456
DBT Daily Diary Card v1.06 (1) / Daily Diary Card

ML Pilot v0.21.48 prod
test-user1@com.us / qwerty
DBT Daily Diary Card v1.06 (2) / Daily Diary Card
Applet password: Qwe123!!!

**Comment by yzenchanka** [comment]
The issue verified as fixed
Notifications are fired offline if:
app is in background
app is closed
app is in background, device is in sleep mode

Video (0.21.62 staging): https://app.screencast.com/GAjeUHUfd5u6s

Environment:
iPhone 7 Plus // iOS 14.4

ML v0.21.62 staging
userseven@ml.com / QAtest123
Applet 2 / A
