### ISSUE TITLE
Stability Tracker 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#1778]
As a user, I want to try to keep a hockey puck over top of the moving dot by tilting my device side to side so that I can test my reaction time.

Requirements: 
We want to implement an activity that shows the user an instruction screen and then starts an interactive experience. It should be similar to [this video ](https://drive.google.com/file/d/1T-GKwLQRO2dL2If3kyH6NWraHIYzEbeT/view)
- Please review[ this doc](https://matter-lab.slack.com/archives/CT1R0BCF7/p1621453998005900) and [this schema ](https://matter-lab.slack.com/archives/CT1R0BCF7/p1621454758014600)
- Here is a [google doc ](https://docs.google.com/document/u/0/d/14DSKl_oXDrOLyAQbNs_oAhdqeR3ryD2vpNX2fuFzupI/mobilebasic)
- More [detailed information](https://matter-lab.slack.com/archives/CT1R0BCF7/p1622788166038200?thread_ts=1622732218.030600&cid=CT1R0BCF7)

Additional Feedback 
1. Add "Tap here to start" in the control bar
2. If the user crashes, pause the screen, move the puck back to the middle and require the user to touch the screen to start again. Add instructions "Tap here to restart" in the control bar
   - reset the internal representation of user position to 0,0 
3.  Score should only decrease after crashing 
4. Add a control bar where the user controls the puck from

**Comment by WorldImpex** [comment]
6 weeks

**Comment by natalia-muzyka** [comment]
@mtg137  @WorldImpex could anyone share the applet schema, please?

**Comment by WorldImpex** [comment]
Done!

**Comment by natalia-muzyka** [comment]
@WorldImpex @mtg137 

**1.** the same question about timestamps as for the Flanker applet, **shouldn't timestamps be displayed as date with time (and milliseconds)?**
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/12eaa364-e9e0-4164-9380-81b633f5f9df)

**2. is this an expected user's score displaying? shouldn't it be similar to the mobile app displaying?**
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/6ca0d597-d05c-4226-b60e-550cad5acc29)

**3. [gyroscope version] to start playing user needs to tap on the "field", it's not clear when you play the first time, 'cause instruction says just tilt the device to keep the disk**

**4. the instruction says to tilt the device in [touch version]**
video: https://www.screencast.com/t/jfN8KtSwjW


**5. question: can I check somehow if the exported data are correct?** : lambda, Lambda Slope, Stim Position, User Position

**6. is there any max wait time when a disk is out of the center(dot)?** sometimes trial restarted even if the disk didn't hit the wall but was just out of the center for 5-15 seconds
video: https://www.screencast.com/t/AdE8FF00yWhP

**7. resuming the activity isn't implemented on this iteration?** after resuming user's score is 0 again
video: https://www.screencast.com/t/A7188DknyHWY

**8. [UI] The score label is too close to the top border:**
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/8b86b562-c88f-4d90-8d7a-de059cc41b36)
iPad Air 2 WiFi / iOS 14.6 / 1536x2048 9.7"
iPad Pro (10,5-inch) MQDX2 / 15.0	/ 1668x2224	10.5"

**9. [iPad Air 2 WiFi / iOS 14.6] Crash after completing the touch activity**  + responses aren't submitted though the "Thank's screen" was displayed (sent a report, can't reproduce anymore)

**10. Long time submitting response (freeze) and opening the Thanks screen, especially on old devices**
video (iPad Pro): https://www.screencast.com/t/e9fiSrRS
video (iPad Air 2): https://www.screencast.com/t/l0hC9U4s1
not reproducible on 12 Pro Max

**11. is there a defined quantity of score that the user loses after the stimulus disk hits the wall?** it is decreased every time on different quantity

**Comment by mtg137** [comment]
@natalia-muzyka - 
could you please upload some videos for this comment?
"Gyro version behaves differently on the devices"

1 - [touch version] Is it acceptable that when the disk is on the left side it reacts to gestures as expected on the right side only?
yes, I think that's expected behavior
the rule for calculating speed/direction of stimulus disc is
( disc position - center point ) + ( finger position - center point )

2 & 3 - I think they are bugs, let me fix them
4 - could you put point (.) before last 3 digits when you use [online converter](https://timestamp.online/)?
![image.png](https://images.zenhubusercontent.com/5fbce3e9259bafeab239c8c3/ef1dd016-aa37-4573-a337-564842fc341a)
( last three digits are milliseconds )

5 - on mobile app side, rounded score is presented to user for convenience
data export will be used by data scientists so I think accuracy is important there
@WorldImpex - could you please confirm?

6 - yeah, I agree with that. I think adding control bar according to additional feedback will solve the problem

7 - I see, I'll fix it
8 - I think it'll be difficult to check lambda and lambda slope values manually
however you can check user pos and stim pos
left side of screen is considered as -1 and right side of screen is 1, so center point is 0

9 -  yes, it is OTCD in the [requirement](https://docs.google.com/document/d/1ToafpbAYB-DMtvuKpt306nHYfzSedAJdNdDJz4XQLRo/edit) and is 15 seconds

For example, lets say that stimulus disc didn't overlap target point for 10 seconds and it overlapped target point after that
a bit later, user made mistake and stimulus disc didn't overlap target point for 5 seconds
in that case, stimulus disc goes back to center point and user has to restart game the same way he should do when disc crashes to boundary

**Comment by mtg137** [comment]
10 - I think in current version, resuming activity will redirect user to starting point of phase that user was on.

@WorldImpex - could you please let us know expected behavior?

11, 12, 13 - let me look into it
14 - I think it is supposed to be decreased by 25%
15 , 16, 18 - let me look into it
17 - @WorldImpex - should we hide skip and back buttons on challenge and test phases?

**Comment by natalia-muzyka** [comment]
@mtg137 
here are videos from some devices (the very beginning of the continuous phase):
iPad Air 2 // iOS 14.6: https://www.screencast.com/t/sIa9Ge1lFOi
Samsung Tab S6 // Android 9: https://www.screencast.com/t/sQQ18EKtS
iPhone 6S // iOS 14.4.2: https://www.screencast.com/t/AJdynoqt
Samsung S20 // Android 11: https://www.screencast.com/t/k7B7aLibVMw

Sometimes disk moves occasionally on all the testing devices, as I mentioned in the #18
On Android it feels like the disk moves faster and sharply, so it is difficult to keep the disk. Sometimes it can even blink and move back to some previous position.
On iOS gyroscope version feels more smooth than on Android but has similar issues with losing control of the disk as well.
Video (Samsung S20): https://www.screencast.com/t/7GSQs1JgAdTA
Video (iPad Air 2 // iO S14.6): https://www.screencast.com/t/AUoaeK5ZTR6

**Comment by natalia-muzyka** [comment]
@WorldImpex @mtg137 do I need to dive into [this requirement doc](https://docs.google.com/document/d/1ToafpbAYB-DMtvuKpt306nHYfzSedAJdNdDJz4XQLRo/edit)?

**Comment by WorldImpex** [comment]
No - We have the stakeholders confirming functionality. It would be good to compare the export with what fields have been requested

**Comment by mtg137** [comment]
I think for we need x, y coordinates for just 2d version
for 1d version, x coordinate is exported on admin panel

and for stimulus disk change rate (7 and 8), it can be derived from 2 and it takes lot of space in the memory, so I dropped it in the data export

https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/bdfb3224-4906-448b-b122-9743878fb16c

**Comment by mtg137** [comment]
I fixed just bugs for touch version in the [PR](https://github.com/ChildMindInstitute/mindlogger-app/pull/1970)

**Comment by natalia-muzyka** [comment]
@mtg137 @WorldImpex 

ML v0.18.18
- Control in this touch version became too easy, I just don't touch the device at all and disk stays in the middle.
- Looks like Challenge phase doesn't have 3 trials. Previously I lost control on disk 3 times within the challenge phase after a short period of time
- Challenge and Focus phases aren't completed automatically. Screen stays open. There are Undo and Next buttons that appear after ~5 minutes of game (for both phases).
**iPhone 8 Plus // iOS 13.3:** Full Video: https://www.screencast.com/t/q53Dr3EMZ8jV
Export files: [https://app.zenhub.com/files/103405139/5fabe921-025a-4303-83fd-9a495966350a/download](https://app.zenhub.com/files/103405139/5fabe921-025a-4303-83fd-9a495966350a/download)
**Samsung S7 // Android 8** Full Video: https://www.screencast.com/t/pNEcgrz3Z9h
Export files: [https://app.zenhub.com/files/103405139/78811cf0-eac3-47c9-9177-2e9f7ebda0ba/download](https://app.zenhub.com/files/103405139/78811cf0-eac3-47c9-9177-2e9f7ebda0ba/download)
**Samsung Tab S6 // Android 9** Stimulus disk behavior is the same as on the smaller devices: https://www.screencast.com/t/oApJpgRZ0q
Reproducible as well on:
Pixel 3XL // Android 10
iPad Pro (10,5-inch) MQDX2	// iOS 15.0

**Comment by natalia-muzyka** [comment]
**Fixed:**
challenge and focus phases are automatically completed (challenge in ~3 min or after 3 crashes of stimulus disk, focus phase is completed in 5 min)

**Issues:**
challenge phase doesn't have 3 trials, I lost control only once because the OTCD time, so in the Focus phase controlling the stimulus disk is still too easy (I can just tap once a ~30 sec on the middle of the tap bar and that's all)


ML v0.18.19 staging
devices: 
iPhone 12 Pro Max	// iOS 15.0.1
iPad Pro 10.5 // iOS 15.0.2
Samsung Tab S6 // Android 9
iPad Air 2 // iOS 14.6

**Comment by WorldImpex** [comment]
@mtg137 Could you move the lambda slope back to 20?

**Comment by WorldImpex** [comment]
1. Could you move the lambda slope back to 20 on the touch version of CST?
2. Remove off-target automatic crash

**Comment by mtg137** [comment]
1. content of applet has been updated on github and applet in demo account was refreshed
2. it is implemented on staging for this [ticket](https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-app/2220)
