### ISSUE TITLE
Update Applet/ Confirmation Page with Clouds Background 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#1824]
Update the background of the applet page and confirmation page with the clouds background seen on the applet list page

**Comment by binaryExDev** [comment]
@WorldImpex I'm not sure what pages you mentioned in the ticket. Could you upload a couple of screenshots for the Applet/Confirmation pages?

**Comment by WorldImpex** [comment]
![IMG_3154](https://user-images.githubusercontent.com/22243307/125947679-e1b15b8a-84b1-4f41-88d4-5631601b5b93.PNG)
![IMG_3153](https://user-images.githubusercontent.com/22243307/125947689-236dc0df-a6a0-4e1a-8972-c37dfb940ab1.PNG)

**Comment by binaryExDev** [comment]
@WorldImpex 
The 1st screenshot has the cloud image and 2nd is the applet screen but what is the confirmation screen you mentioned in the ticket?

**Comment by WorldImpex** [comment]
![File](https://user-images.githubusercontent.com/22243307/125992078-dd089cb5-f30f-444f-ba74-e49a0ff177c0.jpg)

**Comment by natalia-muzyka** [comment]
The background of the applet page and confirmation page is updated.

Issues: 
1) The user name is almost invisible on the applet page because of the white text
https://www.screencast.com/t/Hw9G6iKa

2) [iOS] The progress bar is almost invisible on the confirmation page because of the light progress bar
https://www.screencast.com/t/ELsAmynccTFU

ML v0.16.40 (staging)
Samsung Galaxy S7 Edge SM-G935FD // Android 8.0	
iPhone 6 Plus  // iOS 12.3.1

**Comment by natalia-muzyka** [comment]
Verified as fixed
https://www.screencast.com/t/fRV73afs1ZY

ML v0.17.3(staging)
Samsung Galaxy S7 Edge SM-G935FD // Android 8.0
iPhone 6 Plus // iOS 12.3.1
