### ISSUE TITLE
Show Editor Image Cropping Tool on Image Upload

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#2357]
As an editor, I want to know where my image will be cropped and I want to ability to move the image around so that I can position it on the devices

Requirements 
- Show a image cropping tool when uploading an image that will be the realistic display of the image on the mobile or web device

**Comment by natalia-muzyka** [comment]
@WorldImpex  @astef021 I want to make sure that I understand the purpose of the ticket correctly:
The cropping tool should have fixed frame proportions accordingly to the mobile app/webapp final representation.
So if editor uploads a splash screen then proportions should be 7:10 and editor can move or scale the fixed frame on the uploaded image to find the best result.

**Comment by WorldImpex** [comment]
@natalia-muzyka Yes that is correct

**Comment by natalia-muzyka** [comment]
@WorldImpex Thank you for clarification, then here are my suggestions on how the feature should be updated (please, let me know if something should be changed in the next versions): 
1. Applet image, Activity image: there is a different representation of Applet image(web is a square, mobile app is a circle), I suggest making square frame (fixed proportion 1:1)
2. Splash screen: 
-rectangle frame with a 7:10 proportion (because 700x1000px is required size of image)
-restriction to upload only 700x1000px should be removed, as well as info text in the tooltip
-the "Save original image" should be greyed (only for the Splash screen)
3. For all the rest images(header, response option, labels, drawing, etc) the frame could be editable (as the image bigger side fits the max-height or max-width of the box)?

cc: @astef021 

Current implementation: 
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/71a48164-6950-4e94-95c8-92975e9c083e)

**Comment by natalia-muzyka** [comment]
Related issues;
The uploaded cropped image can't be opened after downloading #775

**Comment by natalia-muzyka** [comment]
@Matchdev120 
2 - the "Save original image" should be greyed or removed to avoid uploading the image with incorrect proportions (only for the Splash screen)

https://www.screencast.com/t/FDQKW5hg5hNg

Looks like we still need to have a limit for uploaded splash image height (or we need to resize the image automatically after cropping to be 700x1000).
There is an issue in ADMIN pdf report if cropped or original image height is bigger or less than 1000px:

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/1e82e607-6c01-45b4-a4d0-30d7abd2f139)

Original images:
1 - https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/10936c61-b73c-471f-b977-d47984443dbb
2 - https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/f51416ff-260a-4e6f-9157-ad664ce1e66c
3 - https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/7d859017-24b6-4fcd-aa80-c25ec5273b10

Cropped images:
2 - https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/dd35ea43-00a2-4cc8-bc14-14a91190e59d
3 - https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/a8c1f385-29e2-412f-ab42-9ed2e6f6a082

**Comment by Matchdev120** [comment]
@natalia-muzyka I'm not able to reproduce #792 and #793. Would you please recheck the issues and let me know the steps if they still happen?

![Screen Shot 2022-03-28 at 7.52.10 AM.png](https://images.zenhubusercontent.com/5e248d759c666007f1a71211/16409f4d-7e44-443a-aa4c-5f1168d21f34)

**Comment by natalia-muzyka** [comment]
@Matchdev120 these issues are still reproducible on my side after clearing cache

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/f1f4e771-2184-420a-a7b1-3def8b2e93e2)

Original images:
![101.jpg](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/d91a3c9c-7b4c-48f1-be3a-a58e0b817498)
![pGRegdLDEdeRcjU3DHXymm (1).jpeg](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/dd220a11-4b3d-4907-ae97-5aae8c491f12)

**Comment by natalia-muzyka** [comment]
All the issues are fixed.
The crop image tool works as per the requirements.

Verified on:
https://admin-staging.mindlogger.org/
Win 10 // Chrome 101.0.4951.54
macOS BigSur 11.0 // Chrome 101
