### ISSUE TITLE
Quantity of the occurrences is not refreshed on the TokenChart behaviors cards after completing the activity

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-app#2358]
**Preconditions**
Mobile app is installed and launched
User is logged in

**Steps to reproduce**
Complete any TL activity (past of future)
Compare the number of occurrences for the selected behavior/behaviors with the Data tab

**Actual result**
Quantity of the occurrences is not refreshed on the TokenChart behaviors cards  after completing the activity even though the token(total) balance is refreshed

**Expected result**
Quantity of the occurrences is refreshed on the TokenChart behaviors cards  after completing the activity

**Video:** https://www.screencast.com/t/gPwalInc

**Environment**
ML v0.18.40 staging
Samsung Galaxy S7 Edge SM-G935FD // Android 8
iPhone X // iOS 14.6
tl_account9@mail.com	123456
applet: timestamp test
tl_account10@mail.com	123456
applet: tl applet test
Applet password	Qwe123!!!

**Comment by jj105** [comment]
I think we need to check this feature after 0.18.41 is deployed

yesterday, I updated mobile app and backend to [fix this issue](https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-admin/1437) on mobile data tab as well
( backend is deployed but mobile app is not deployed )

I think that's why frequency feature is failing on mobile app data tab.

**Comment by natalia-muzyka** [comment]
@jj105 thank you for the clarification.
@WorldImpex I've just retested this issue on 0.18.41, it is not reproducible.
The ticket can be closed.

Video: https://www.screencast.com/t/NE4U0L3b

Environment:
ML v0.18.41 staging
Samsung Galaxy S7 Edge SM-G935FD // Android 8
iPhone X // iOS 14.6
