### ISSUE TITLE
Do not allow Cumulative/ Token Items to be moved

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#2410]
1. Cumulative items cannot be moved within an activity or between activities 
2. Individual TokenLogger items cannot be moved within an activity or between activities. Only  all TokenLogger items can be moved

**Comment by natalia-muzyka** [comment]
@devbtech @WorldImpex 
1. fixed
2. there should be the ability to move TokenLogger items together
past: behavior tracker item + summary; 
future: select timing + behavior tracker item + summary; 
Currently, it's not possible, because "move" button is missing on the TL items.
Should we leave this implementation?

**Comment by WorldImpex** [comment]
Lets leave it for now @natalia-muzyka

**Comment by natalia-muzyka** [comment]
Created and backlogged a separate ticket for the #2 case.
Verified and closed the current ticket.

Environment:
https://admin-staging.mindlogger.org/
Win 10 // Chrome 98.0.4758.102
