### ISSUE TITLE
The summary screen is shown on the mobile app when there are no alert responses and score ID to show

### ISSUE THREAD

**Issue by MaksimYurys** [ChildMindInstitute/mindlogger-app#2799]
Preconditions:
The user is logged in to the mobile app
The user has an applet with activity.
The activity has  turned on the summary screen without scoreID and alert state 

Steps to reproduce:
1. Pass an activity.
2. Pay attention to the screen

Actual result:
The summary screen is shown on the mobile app screen

Expected result:
If the editor turns on the summary screen without scoreIDs or alerts, then no summary screen is shown

Video: https://images.zenhubusercontent.com/103405139/f589710b-a0b7-4cc8-86ca-9d419fd21ab4/fb6fbcd0_d4f5_4d60_a5c8_76f0d6924b96.mp4

Environment:
ML v0.21.40
iPhone 8 // iOS 14.7.1
Samsung Galaxy S8 // Android 8
JhoneeMind@gmail.com // Qqww!123
ConfReports 2 // activity 2
aplet password - Qqww!123

**Comment by MaksimYurys** [comment]
Verified as fixed.

Video: https://images.zenhubusercontent.com/103405139/d69225fe-bed1-4df5-b245-085ab1d95bda/b0b3668b_4c21_4f08_8053_ad28ce4a98ad.mp4

Environment:
MindLogger v0.21.42
iPhone 8 // iOS 14.7.1

**Comment by natalia-muzyka** [comment]
The issue is reproducible. There are no alert options in responses, and an empty summary screen is shown at the end of the activity.
Expected: Summary screen is allowed on the builder side. If there were no Score IDs added on the Reports tab, and there were no selected alert options on mobile app then the Summary screen shouldn't be shown.

Video: https://www.screencast.com/t/84OYTcYJzTZ

Environment:
https://admin-staging.mindlogger.org/
ML v0.21.48 staging
Samsung Galaxy Tab S6 SM-T865 // Android  9.0
Apple iPad 9th gen (2021) / iOS 15.5
user-stg@ml.com / 123456
Config reports / Test A (1) (1)

**Comment by natalia-muzyka** [comment]
Verified as fixed: https://www.screencast.com/t/NLGo3CvkZy1

Environment:
ML v0.21.53 staging
iPhone 7 // iOS 13.1.1
iPhone 13 // iOS 15.6
Samsung Galaxy S7 // Android 8
Google Pixel 5a // Android 11
