### ISSUE TITLE
Icon Missing From Summary Screen in Report

### ISSUE THREAD

**Issue by e-kass** [ChildMindInstitute/mindlogger-app#2858]
Icon to the left of the flagged subscales are missing in the summary screen generated in the report.

See correct here - Screenshot of Summary Screen that is generated at the end of the applet/activity flow:

![MicrosoftTeams-image.png](https://images.zenhubusercontent.com/6310fa4035485166fdf9897e/d8d02fe4-9b90-4bb7-bd61-2521606dc2e8)

See incorrect here - Screenshot of Summary Screen that is generated in the beginning of the emailed report:

![Screen Shot 2022-09-01 at 4.12.39 PM.png](https://images.zenhubusercontent.com/6310fa4035485166fdf9897e/5899f2ee-7d2f-42f5-aec1-fa86684be609)

**NOTE** The two screenshots refer to different test cases. They are merely to show the icon showing up in the former and missing in the latter.

**Comment by natalia-muzyka** [comment]
@Tom1204 
Video: https://www.screencast.com/t/Xq2d2TAtQr

Design:
https://www.figma.com/file/VYuZ9vFaPfK6JnXeAXG8wW/Pre-SRC-Features?node-id=458%3A5374

Environment:
https://admin-staging.mindlogger.org/
user-stg@ml.com / 123456
Config report v14 / Test A
Applet password: Qwe123!!!

**Comment by natalia-muzyka** [comment]
@Tom1204  The icon is present but it is too pixelated. Also, it is trimmed on the top (Windows Chrome).
Could you check if the appropriate icon is used? Here is the design:
https://www.figma.com/file/VYuZ9vFaPfK6JnXeAXG8wW/Pre-SRC-Features?node-id=112%3A2248

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/469f05f0-3080-407e-8a27-763079a63b42)

Environment:
https://admin-staging.mindlogger.org/
Win 10 / Chrome 106
macOS 10.15 / Chrome 106 / Safari 13.1.2
new_user@ml.com / 123456
user id test / config report
Applet password: Qwe123!!!

**Comment by Tom1204** [comment]
@Damirkhon, pls look there is problem with css, as I think
![Screen Shot 2022-10-31 at 4.38.20 PM.png](https://images.zenhubusercontent.com/635a8bfd8a277d380fa24074/9594a0ee-9b08-4dbb-9ce2-84b9460a247f)

**Comment by Damirkhon** [comment]
changed icon to more high-resolution one. please check and merge @Tom1204

**Comment by natalia-muzyka** [comment]
@Damirkhon 

The resolution is fixed, but there is one more issue.
The exclamation icon should be displayed only near the **flagged** score.
It is displayed near every score now. Mobile app behavior is correct. The issue is only on the report side.

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/46f5b2c0-6abe-44c3-bd7a-f842ab236e36)

cc: @yzenchanka

Environment:
https://admin-staging.mindlogger.org/
Win 10 / Chrome 106
new_user@ml.com / 123456
user id test / config report
Applet password: Qwe123!!!

**Comment by Damirkhon** [comment]
@natalia-muzyka Done
@karser please review PR [#13](https://github.com/ChildMindInstitute/mindlogger-report-server/pull/13)

**Comment by yzenchanka** [comment]
The issue is fixed: the exclamation icon is displayed only near the flagged score
Environment:
https://admin-staging.mindlogger.org/
Win 10 / Chrome 107
iPhone 7 Plus // iOS 14.4
userone@ml.com / QAtest123
Test reports(1)/ Activity A
Applet password: Asd123!!!
![image.png](https://images.zenhubusercontent.com/6316e4697ddec12592e31aaa/e0f07e80-4703-4652-ac58-4dbc156d193d)

**Comment by natalia-muzyka** [comment]
Verified as fixed.

Environment:
https://admin-staging.mindlogger.org/
Win 10 / Chrome 107
new_user@ml.com / 123456
user id test / config report
Applet password: Qwe123!!!
