### ISSUE TITLE
⚠️⏰ App icon's badge number doesn't increment; `PushNotificationIOS.setApplicationIconBadgeNumber(1)`

### ISSUE THREAD

**Issue by shnizzedy** [ChildMindInstitute/mindlogger-app#330]
A few things about this line:

https://github.com/ChildMindInstitute/mindlogger-app/blob/c9b26b5a01649c5f3c8e8b7bb32a11532d744ad9/app/services/pushNotifications.js#L39

- [ ] I read this code as only ever setting the badge to exactly `1` rather than incrementing. I think we'd want the number of un-responded-to notifications, not just always `1`, right?
- [ ] This behavior seems to be triggered when a notification is scheduled (ie, setup) rather than when one occurs (ie, at the time a user is notified)
- [ ] The line is missing its terminal semi-colon

**Comment by shnizzedy** [comment]
related https://github.com/ChildMindInstitute/mindlogger-app/issues/307

**Comment by InheritxSolution** [comment]
If we want to manage the badge count dynamically then the best way to achieve this functionality is the push notification so the badge directly comes up with the push notification and badge display dynamically.

Please check this link [https://stackoverflow.com/a/5962607](url).

Managing this count is typical process with the local notification because for that we need to track those count locally and manage with every schedule notification and at the time of resetting those count we need to make copy of the already scheduled notifications and at the time of resetting the data we need to re-schedule the notification again.

Let me know if you want more explanation for the same.

**Comment by shnizzedy** [comment]
* [getApplicationIconBadgeNumber()](https://facebook.github.io/react-native/docs/pushnotificationios#getapplicationiconbadgenumber)

**Comment by binarybottle** [comment]
From this morning's standup meeting, I understand that incrementing a badge number is difficult with local notifications.  We will set this issue aside and tackle it later.

**Comment by binarybottle** [comment]
I'm seeing badge numbers bigger than one.  Am I missing something?
![IMG-0016](https://user-images.githubusercontent.com/236532/71134830-b1030980-21cd-11ea-991d-dcdd99cdfae7.PNG)

**Comment by shnizzedy** [comment]
A badge, as discussed in #306, is circled in this screenshot: ![badge on MindLogger](https://user-images.githubusercontent.com/5974438/71187894-fe26c000-224d-11ea-91b3-0cd96aca9552.PNG)

**Comment by binarybottle** [comment]
@Eden2016: 

> So what I’ve figured out about this issue is… that the badge count can be increased only from the server-sent notifications (ex. Firebase notif. service). And we can increase the badge number manually only when the app is open.

**Comment by shnizzedy** [comment]
I think `Object.keys(overdue).length` is the value we want in the badge:

https://github.com/ChildMindInstitute/mindlogger-app/blob/5fd1f3c6f2116c42a747bbd6d9721ec50218e96a/app/components/ActivityList/sortActivities.js#L58

https://github.com/ChildMindInstitute/mindlogger-app/blob/e739b490216b0f2fcca6c54d30430ea108a7e14f/app/components/ActivityList/index.js#L24

**Comment by WorldImpex** [comment]
Badge shows with notification and disappears after push notification is selected
