### ISSUE TITLE
App Crashes When User Looks at Data Screen

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#625]
Expected Results: User can look at reports for any amount of time he or she wants without interruption 
Actual Results: User gets only a few minutes on the report before the app crashes 

Environment: iPhone 6s 13.3/ v0.9.11 -NIMH

![File (1).jpg](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/e212b041-f0fe-4e38-a8d3-10adbb7a73d8)

**Comment by shnizzedy** [comment]
Here's the crashlog from this event: [crashlog.crash](https://github.com/ChildMindInstitute/mindlogger-app/files/4047486/crashlog.crash.txt)

**Comment by henryrossiter** [comment]
I'm having trouble replicating this. Is the issue only on one the HBN applet or are you experiencing it on multiple applets?

**Comment by shnizzedy** [comment]
I've also not been able to replicate

**Comment by WorldImpex** [comment]
@shnizzedy / @henryrossiter I sent crash reports through testflight if that helps. I am unable to recreate it today on dev or prod. We can just backlog this for now and move on

**Comment by shnizzedy** [comment]
I got the [crashlog above](https://github.com/ChildMindInstitute/mindlogger-app/issues/625#issuecomment-573172730) from TestFlight.

**Comment by shnizzedy** [comment]
I have now been able to replicate this bug with `5e1f4f47720011229c1a15d2` ("Healthy Brain Network (NIMH content) 2") on [prod](https://api.mindlogger.org/api/v1). I think it's related to https://github.com/ChildMindInstitute/mindlogger-app/issues/678 but in [AppletData](https://github.com/ChildMindInstitute/mindlogger-app/tree/master/app/components/AppletData) rather than in [screen/Widget](https://github.com/ChildMindInstitute/mindlogger-app/blob/c32ff44adcd4bb605a4dcd5a488c1c72e181db53/app/components/screen/Widget.js).

**Comment by WorldImpex** [comment]
App does not crash now with an empty data tab
