### ISSUE TITLE
Add question to list on data tab

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#630]
Expected Result: When user navigates to data tab, the question and answer should be displayed along with the history of answers over the last 7 days 
Actual Results: User does not see the question related to the user's answer 

Environment: iPhone 6s 13.3/ v0.9.11

![download.jpeg](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/1617c415-1aa9-4b46-b66e-f06e6aa630ee)

**Comment by Eden2016** [comment]
I can’t determine what is happening on #630 without reviewing logs on the back-end side. After finishing an activity the app is sending the list of responses for each question but I can’t confirm if they are being stored or not. It seems not because when the app get all the responses in the data tab I don’t see responses for those questions except for Morning Activity. Also after finishing Evening activity still appears as Due although I completed it several times.

![Screen Shot 2020-01-13 at 11 37 39](https://user-images.githubusercontent.com/16896205/72275435-eac40600-35fb-11ea-825f-21092ad22b66.png)

As you can see here I have responses for the Morning questions but not from the Evening downloaded from the back-end

![Screen Shot 2020-01-13 at 11 38 00](https://user-images.githubusercontent.com/16896205/72275462-f7485e80-35fb-11ea-9667-c90729a5276a.png)

And here you can see that the Evening activity is still Due although I completed it several times.

@shnizzedy  How do you propose should I continue on with this issue? I spend a lot of time debugging several components of the app trying to decipher any error on the app side but I can’t find none. If I could check the back-end logs maybe I could understand what’s happening and solve the issue.

**Comment by shnizzedy** [comment]
@Eden2016 is the mobile app expecting to get the questions in that call? I can add that to the response from the backend. How should it be keyed?

---

For live logging on the backend, I [run a local Girder for MindLogger](https://github.com/ChildMindInstitute/mindlogger-app-backend#installation) on a local database and use [ngrok](https://ngrok.com/) to access that endpoint from my mobile app.

**Comment by Eden2016** [comment]
@shnizzedy yes there is an action to get all the responses for all activities but only the Morning activity's responses are showing up. The structure of the responses should be similar to Morning responses array.

**Comment by shnizzedy** [comment]
@Eden2016 I opened a new issue about the responses to more than one activity not showing up (#659).

This issue is about how in [the screenshot at the top](https://camo.githubusercontent.com/533385209d785336883465d763dfe2ec7b72ff6b/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3565313333366631623234303235613762323635343437352f31363137633431352d316161392d346234362d623636652d663036653661613633306565) the question "Have you taken your activity monitor off since the last assessment?" should appear but does not.

I'm not sure if the app expects to get that question from the `GET /responses` call or if it knows it from the screen/item/question's URL or ID.

**Comment by Eden2016** [comment]
I think we need to get those responses from that endpoint because on the Data Tab we need to show up all the responses in a timeline fashion. And that screen is reading from the app state but since there is no data regarding those questions/responses it doesn't how nothing.
![Screen Shot 2020-01-13 at 13 27 22](https://user-images.githubusercontent.com/16896205/72281414-82c7ec80-3608-11ea-8fed-98c48ef66c9f.png)
![Screen Shot 2020-01-13 at 13 27 40](https://user-images.githubusercontent.com/16896205/72281421-865b7380-3608-11ea-8b01-d6cefb1bc2db.png)

**Comment by shnizzedy** [comment]
@Eden2016 how did you get them to show in those screenshots?

**Comment by shnizzedy** [comment]
![curiouser and curiouser](https://media1.tenor.com/images/66c582e991a452b560b69218b22626d3/tenor.gif).

I'm beginning to suspect this issue is actually a schema problem. In trying to replicate and trace the bug, I've had success in plotting responses instead:

![data tab screenshot](https://user-images.githubusercontent.com/5974438/72293913-79e41480-3622-11ea-9cde-50cde9e161c2.jpg)

**Comment by hotavocado** [comment]
@shnizzedy @WorldImpex 
Sorry should have addressed this earlier, this is 100% a schema issue. The applets I made do not have a "schema:description" key in the item files (unlike this item here https://github.com/ReproNim/reproschema/blob/master/activities/EmaHBNEvening/items/energy#L9). The ML data panel seems to use this key to get the question name. I will work on adding this into the conversion script.

**Comment by shnizzedy** [comment]
I think it makes sense to use the "question" key as a fallback at least!

**Comment by hotavocado** [comment]
@shnizzedy I second this

**Comment by shnizzedy** [comment]
To resolve this issue, then, we can update the app to fall back on `question` if `description` is not present. :sunglasses:

**Comment by hotavocado** [comment]
this is probably where the change needs to happen: 

https://github.com/ChildMindInstitute/mindlogger-app/blob/master/app/components/AppletData/ItemChart.js#L123

**Comment by WorldImpex** [comment]
Fixed

![IMG_0194.PNG](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/d75aac9e-3b45-424a-8fac-d653e4588688)
