### ISSUE TITLE
multi-select conditional logic parsing 

### ISSUE THREAD

**Issue by hotavocado** [ChildMindInstitute/mindlogger-app#636]
I'm having trouble getting conditional logic for questions that depend on a multi-select question to work.

ex

item1 is a multi-select question with choices 1, 2, 3, 4
item1a should only be visible when the user selects choice 1
item1b should only be visible when the user selects choice 1 or choice 2

Currently the visibility object in the schema looks like:

"item1" : true 
"item1a" : "item1.includes(1)" 
"item1b" : "item1.includes(1) || item1.includes(2)"

However this doesn't work, item1a and item1b both show up regardless of which choices are picked for item1.

**Comment by henryrossiter** [comment]
I found the root of the issue. The package that we are using to evaluate the conditional logic, 'expr-eval', is not able to handle operations on objects. Therefore, since Arrays are objects, ```Array.prototype.includes()``` always throws a ```TypeError```:

```TypeError: Array.prototype.includes requires that |this| not be null or undefined```

The issue with 'expr-eval' is documented here: https://github.com/silentmatt/expr-eval/issues/169 although I should be able to solve this within MindLogger's code base.
