### ISSUE TITLE
Do not allow double clicking of Activity buttons in App

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#720]
Expected Results: User clicks activity button and opens only 1 instance in MindLogger App
Actual Results: User can double click activity button and open 2 or more instances  in MindLogger App

** This is only for buttons in app. Not for buttons in an applet. **

**Comment by sergeysemenuta** [comment]
The issue is fiexed only for the events but the same issue is reproduced after double tapping on other elements on the app.
Affected screens:
Settings screen (After double tapping on the cog icon)
Sign up screen (After double tapping on the "Ne User" link)
About MindLogger  (After double tapping on the "What is MindLogger?" link)
Change Password screen  (After double tapping on the "Change Password" item)
Scan QR screen

Video: https://www.dropbox.com/s/td29ds4tb1xfnb1/2020-05-04_12-47-32.MP4?dl=0

**Comment by WorldImpex** [comment]
task ticket created on #982
