### ISSUE TITLE
All New Users should have access to Mindlogger as a User

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#728]
When a new user signs up, they should be automatically added to the MindLogger Demo app as well as the NIMH applet.

**Comment by henryrossiter** [comment]
Should all new users be added as new users to two existing applets? Or create a new instance of the applets for every new user, so that they are the only user in the applets? 

The first option will take up much less computing power & database space but the study coordinator would have access to everyone's data.
