### ISSUE TITLE
❗️Visibility is broken for new applets

### ISSUE THREAD

**Issue by hotavocado** [ChildMindInstitute/mindlogger-app#771]
Recently the visibility (or skip logic) stopped working for my applets. However it still works on the cached "Healthy Brain Network (NIMH content) 2" applet that is added by default to every account. 

I checked the 'visibility' object for one activity in the cached and new applet in the response body of get/user/applets, and they look the same. 

cached applet (skip logic works)
https://docs.google.com/document/d/1Xl_ksGV87t_dZ39KprybzfM7b77aFPSThUN82JbCBL8/edit?usp=sharing

new applet (skip logic broken)
https://docs.google.com/document/d/1gWOdD-IME_jsRd67sMsxqH1tAgzlW3MNAIUAG53B-6k/edit?usp=sharing

**I created a simple test applet here, the skip logic is broken for this applet:**
https://raw.githubusercontent.com/hotavocado/visibility-test/master/protocols/visibility-test/visibility-test_schema

Here is the 'visibility' object in the activity schema:
https://github.com/hotavocado/visibility-test/blob/3b4fd382edd0f166179b43d3077613430e04f3d4/activities/test/test_schema#L35-L38

Would someone be able to figure out why this isn't working?

**Comment by WorldImpex** [comment]
Here is a video of conditional logic being broken. Since I selected energy drinks, I should have been forwarded to the energy drink question as my next and skipped over the water and milk

![RPReplay_Final1582292701 (1)](https://user-images.githubusercontent.com/22243307/75046653-81090880-5493-11ea-935b-99ce920323a0.gif)

**Comment by henryrossiter** [comment]
There are 3 seperate reasons that conditional logic on hbn v0.20 isn't working on wil's account:
- The applet was uploaded before the variables were renamed in commit /5d2e9b4c57b1da509f93806b9d6f4396527d312e . Cached applets aren't automatically updated when the schema is changed on github, so the applet needs to be reuploaded or refreshed before it will work.
- Variable names can't use dashes! Visibility objects are parsed as JavaScript boolean statements. JavaScript variables cannot contain - because that is parsed as the subtraction operator. For example, since-activity-monitor is parsed as since minus activity minus monitor . I would recomment switching to camelCase variables.
- The visibility object stored in the database was stored in didn't contain the @list
key. Conditional logic to fix this is in https://github.com/ChildMindInstitute/mindlogger-app/pull/782
